name: sync up to codecommit

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'
permissions:
  id-token: write   # This is required for aws oidc connection
  contents: read   # This is required for actions/checkout
  pull-requests: write  # This is required for gh bot to comment PR


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::992382551538:role/github-action
          aws-region: us-east-1
          role-session-name: github-action

      - name: Sync up to CodeCommit
        uses: tsgit18/sync-up-to-codecommit-action@v1
        with:
          repository_name: test_repo
          aws_region: us-east-1
