name: sync up to codecommit

on:
  push:
    branches:
      - main
      - feature/cypress

permissions:
  id-token: write   # This is required for aws oidc connection
  contents: read    # This is required for actions/checkout
  pull-requests: write  # This is required for gh bot to comment PR

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git to trust the workspace directory
        run: git config --global --add safe.directory /github/workspace

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::992382551538:role/github-action
          aws-region: us-east-1
          role-session-name: github-action

      - name: Sync up to CodeCommit
        run: |
          # Configure Git to trust the workspace directory inside the Docker container
          docker run --rm \
            -e AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }} \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -v "${{ github.workspace }}":/github/workspace \
            -w /github/workspace \
            tsgit18/sync-up-to-codecommit-action:v1 sh -c "git config --global --add safe.directory /github/workspace && /entrypoint.sh"
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
