name: sync up to codecommit

on:
  push:
    branches:
      - main
      - feature/cypress

permissions:
  id-token: write   # This is required for aws oidc connection
  contents: read    # This is required for actions/checkout
  pull-requests: write  # This is required for gh bot to comment PR

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git to trust the workspace directory
        run: git config --global --add safe.directory /github/workspace

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::992382551538:role/github-action
          aws-region: us-east-1
          role-session-name: github-action

      - name: List branches for debugging
        run: git branch -a

      - name: Check out the main branch
        run: git checkout main

      - name: Sync up to CodeCommit
        run: |
          git remote add codecommit https://git-codecommit.us-east-1.amazonaws.com/v1/repos/test-repo
          git push codecommit main --force
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
