name: Snyk Security Scan for Terraform
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities in Terraform files
        uses: snyk/actions/terraform@latest_version
        with:
          working-directory: path/to/terraform/files
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
